# ============================================================
# query.py - Modèle SQLAlchemy Query
# ============================================================
# Table: queries
# Colonnes:
#   - id: Integer, Primary Key, auto-increment
#   - user_id: Integer, Foreign Key → users.id
#   - query: Text, not null
#   - reponse: Text, not null
#   - sources: JSON (liste des chunks sources utilisés)
#   - created_at: DateTime, default=now
# Relations:
#   - user: relationship → User
# ============================================================
from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Text
from sqlalchemy.sql import func
from backend.db.base import Base 
class Query(Base):
    __tablename__ = "Query"
    
    id = Column(Integer, primary_key=True, index=True)
    query = Column(Text, nullable=False)
    reponse = Column(Text, nullable=False) # Response generated by the RAG chain
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    user_id = Column(Integer, ForeignKey("users.id"))